### ISSUE TITLE
希望我们可以建立一个平台，让国内的程序员可以更多和你这样在新加坡的人沟通，提供过去的经验。帮助更多的人呢

### ISSUE THREAD

**Issue by kangqiwang** [623637646/996.Leave#1]

**Comment by miryuan** [comment]
这里不就可以沟通吗?不过这次996icu事件,估计github会被列入墙名单候选

**Comment by XUJINKAI** [comment]
列入就列入吧，真把GitHub墙了大多数程序员就可以歇了，也不知最后谁着急

**Comment by WangSiwang** [comment]
哈哈哈，我真期待墙的那一天。只怕墙都会被攻破。zf也应该清楚疏而不是堵

**Comment by 623637646** [comment]
有海外工作经验，想和大家分享的，可以发Pull Request给我，我会整合到这个repo。 我只发了个 新加坡的分享，欢迎各个其他国家的分享。

回头我会按照国家，把文章进行分类。

**Comment by 623637646** [comment]
已贴出猎头信息， 详情搜索 “招聘”
