### ISSUE TITLE
普通二本应届生，有人讨论下赴日工作路线吗？

### ISSUE THREAD

**Issue by arakitatsuzou** [623637646/996.Leave#114]
我现在N1 170+，下学期大四，在学iOS，在学校老师的公司实习，大四打算再考个托业800/900+然后毕业先尝试乐天这类重英语的企业，不行就联系这个项目的HR或ourcoders看到的HR，最后也不行就先用贴吧或其它中介出去再说。
有类似情况的分享下赴日路线吗？

**Comment by anti715** [comment]
去日本除非去当地留学或者外语很好啊

**Comment by arakitatsuzou** [comment]
@623637646 请求删除
