### ISSUE TITLE
已经搜索过一些网上资料,想请教一下在新人士,新加坡普通人对于LGBT和出柜的看法

### ISSUE THREAD

**Issue by KSroido** [623637646/996.Leave#136]
利益相关LGBT人士, 想请教一下

**Comment by jschwinger233** [comment]
华人年轻人里还是有一定接受度, 不过整体社会接受度就不太行了, 更别说10%+人口比例的穆斯林. 在大型互联网公司内出柜问题不大, 不会影响工作.

**Comment by jschwinger233** [comment]
虽然我个人看不到在工作环境里出柜的好处, 不过这是个人意愿, 自己舒服就好.

**Comment by KSroido** [comment]
感谢您的回函，尤其是10%穆斯林那句，帮助颇深
再次感谢

zc ***@***.***> 于 2022年3月11日周五 15:31写道：

**Comment by KSroido** [comment]
> 虽然我个人看不到在工作环境里出柜的好处, 不过这是个人意愿, 自己舒服就好.

另外请问一下，在可预见的未来内，新加坡立法机构有合法化LGBT的趋势吗？（就您个人目前了解而言）

我听说那个禁止同性恋的法案目前也一般不审理了，请问实际情况是这样吗？
感谢~！

**Comment by jschwinger233** [comment]
犯法的是"男性同性性行为"而不是同性恋, 所以这一条法律本身也不太容易执行, 因为需要捉奸在床, 不过隔壁印尼就钓鱼执法这么抓过约炮的同性恋, 所以想执行也能执行.
当前确实不怎么管, 也有法学家呼吁直接起诉到高院修改法律, 每年也有 pink dot 运动, 不过从街头调查来看, 完全没有去犯罪化的趋势....毕竟是多民族国家, 要协调多种宗教和民族的平衡.

**Comment by KSroido** [comment]
感谢，基本明白了
再问一个您的主观问题吧
您觉得新加坡是一个民主国家吗？新闻自由如何？

**Comment by jschwinger233** [comment]
https://www.bbc.com/zhongwen/simp/world/2015/05/150525_singapore_taiwan_gay_marriage_song 
我个人认为不太民主, 槽点很多, 不过这世上每一个政府槽点都很多, 凑合着过吧...

**Comment by KSroido** [comment]
好的，thanks for your time!

zc ***@***.***> 于 2022年3月11日周五 18:17写道：

**Comment by KSroido** [comment]
done
