### ISSUE TITLE
Discord邀请 安全可靠，里面已经有很多朋友了

### ISSUE THREAD

**Issue by kylesliu** [623637646/996.Leave#31]
# Discord邀请 安全可靠，里面已经有很多朋友了
<a href="https://discord.gg/6E3kzEG">
    <img src="https://xpnet-public.oss-cn-hangzhou.aliyuncs.com/color_admin_v4.3/admin/documentation/assets/images/d76f9d66fa5126b1b655c2d99bbc2.png" alt="Build Status">
</a>

[Discord Link](https://discord.gg/stSSHgY)

>大家好，这里有个关于996的Discord交流群，里面有同步GitHub的PR和Slack的信息也有吐槽工作的交流等频道。 大家可以来这里交流、学习、吹牛逼。
## 怎么在内地上discord
编辑电脑 hosts文件（你懂得）
```bash
104.16.248.144   dl.discordapp.net
104.16.60.37   gateway.discord.gg
104.16.11.231  status.discordapp.com
104.16.9.231    cdn.discordapp.com
104.16.59.5  discordapp.com
104.16.248.144 media.discordapp.net
104.16.249.144 images-ext-2.discordapp.net
104.16.248.144 images-ext-1.discordapp.net
151.101.78.214  static-cdn.jtvnw.net
```

**Comment by a33151** [comment]
我加入不了。能邀请我吗？

**Comment by kylesliu** [comment]
> 我加入不了。能邀请我吗？

刚才测试了链接地址时好用的，应该时由于G''F''ww的问题。

kyle.liu.cn@gmail.com 这是我邮箱我可以帮你入群。

**Comment by a33151** [comment]
谢谢 我再次尝试加入已经OK了

> > 我加入不了。能邀请我吗？
> 
> 刚才测试了链接地址时好用的，应该时由于G''F''ww的问题。
> 
> [kyle.liu.cn@gmail.com](mailto:kyle.liu.cn@gmail.com) 这是我邮箱我可以帮你入群。
