### ISSUE TITLE
表示支持，爱自己的祖国，但拒绝被剥削。

### ISSUE THREAD

**Issue by orochitian** [623637646/996.Leave#4]
如果国内的公司都慢慢变成996，那只会有越来越多的人选择离开。
借用郭德纲老师的一句话就是，我爱它，可TM谁爱我啊？

**Comment by hui305** [comment]
Country is not the Government

**Comment by epicGeek** [comment]
@hui305 D已经绑定了国家和ZF D>=国家，D>=ZF， ZF约等于国家
