### ISSUE TITLE
希望有更多澳洲it工作信息

### ISSUE THREAD

**Issue by fuzheng1998** [623637646/996.Leave#44]
未毕业留学党一枚，想知道当地it找工作有知乎说那么难么，还有相关移民信息

**Comment by ccwukong** [comment]
澳洲其实是最容易移民的国家之一，因为移民打分标准明确。

澳洲找工作难是因为澳洲的大部分公司需要有经验的专业人士，不管你是搬砖还是搞金融的。在澳洲，名校效应不是那么明显，有工作经验的“二流大学”（澳洲本地人不分什么一流二流）候选人会比澳洲八大（中国人自己总结的）的毕业生有更高的机会拿到offer. 我个人曾经从新加坡offshore申请拿到过两家澳洲顶级公司的offer，最后因为某些个人原因放弃了全家搬去悉尼的机会。所以我感觉国内BAT的员工们有很高的机会拿到澳洲顶级公司的offer，只要能过了英语口语关。

最近一两年澳洲的工签改革了很多，尤其是取消457签证，由TSS签证替代（两年期和四年期，两年期的不能申请pr，四年期的在第三年由公司担保申请pr），以减少不合格的“技术员工”混pr的可能性，但根据我个人面试澳洲公司的经验，但凡是码农，很少有不给4年TSS的可能，因为SE一直是澳洲的紧缺专业。

还有就是澳洲的工作申请流程比较短，我的两个offer都在一个月内搞定，相比一些美国公司动则两三个月的面试流程，澳洲真的是非常简洁流畅。

至于留学党，只能说在你学习期间多争取实习机会，不是那种去7-11和餐馆打工那种，一定要和你专业相关的，哪怕是做freelancer也行，这样能为你的简历加分不少。
