### ISSUE TITLE
要不要每一个国家都放一个文件夹，然后不同公司一个README

### ISSUE THREAD

**Issue by HarrrrryLi** [623637646/996.Leave#58]
这样大家在同一个国家不同公司也好一起弄一些。

**Comment by 623637646** [comment]
首先感谢提出宝贵建议。
对于读者来讲，最感兴趣的是某个国家的生活工作相关的信息，而不是某个公司。
当初按国家分类，同一国家的不同公司放到一个地方的目的就是让多人共同维护这个国家的信息。
如果我们按公司分类，那么肯定会造成同一个国家的信息，有重复或者不一致。这会造成读者理解的困扰，阅读成本增加和维护成本的增加。
