### ISSUE TITLE
建议起草一份标准回答格式，以便更多的人分享自己的经历和提供帮助

### ISSUE THREAD

**Issue by hotdogicn** [623637646/996.Leave#8]
如题，建议起草一份标准回答格式。

作为身在美国的程序员，我本人很愿意分享我的经历、和各位取得联系，并进一步探讨我所能够提供的帮助。

**Comment by 623637646** [comment]
已经新建了模板 https://github.com/623637646/996.Leave/blob/master/CountryTemplate.md
谢谢你的支持。
