### ISSUE TITLE
>  讽刺的是为了实现这样的价值观会要求你离开父母去另外一个国家，着实让人蛋疼菊紧。。

### ISSUE THREAD

**Issue by Jingxiao-Han** [623637646/996.Leave#85]
>  讽刺的是为了实现这样的价值观会要求你离开父母去另外一个国家，着实让人蛋疼菊紧。。

每个人的价值观不同，取舍也不同。不是说国外就一定好，适合自己的才是最好的！
我不觉得有什么讽刺的，如果在国内外地工作，就算是955，一年又能见几次父母呢？离开父母也要看具体情况，我每年都会休假三周回国看父母，父母也会每年来我这住三个月到半年，到底谁见父母见的少呢？

_Originally posted by @xuechen628 in https://github.com/623637646/996.Leave/issues/33#issuecomment-481465401_

**Comment by rxy1212** [comment]
说得对，现在一个人在深圳工作也就过年有不到一周的时间能回家。

**Comment by fengjianyun** [comment]
很无奈，但除了父母还有孩子。
